package bean;
// Generated 22/09/2023 07:47:46 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VendedorPbt generated by hbm2java
 */
@Entity
@Table(name="vendedor_pbt"
    ,catalog="sistema4"
)
public class VendedorPbt  implements java.io.Serializable {


     private int idvendedorPbt;
     private String nomePbt;
     private String emailPbt;
     private String telefonePbt;
     private String enderecoPbt;
     private int sexo;

    public VendedorPbt() {
    }

    public VendedorPbt(int idvendedorPbt, String nomePbt, String emailPbt, String telefonePbt, String enderecoPbt, int sexo) {
       this.idvendedorPbt = idvendedorPbt;
       this.nomePbt = nomePbt;
       this.emailPbt = emailPbt;
       this.telefonePbt = telefonePbt;
       this.enderecoPbt = enderecoPbt;
       this.sexo = sexo;
    }
   
     @Id 

    
    @Column(name="idvendedor_pbt", unique=true, nullable=false)
    public int getIdvendedorPbt() {
        return this.idvendedorPbt;
    }
    
    public void setIdvendedorPbt(int idvendedorPbt) {
        this.idvendedorPbt = idvendedorPbt;
    }

    
    @Column(name="nome_pbt", nullable=false, length=45)
    public String getNomePbt() {
        return this.nomePbt;
    }
    
    public void setNomePbt(String nomePbt) {
        this.nomePbt = nomePbt;
    }

    
    @Column(name="email_pbt", nullable=false, length=45)
    public String getEmailPbt() {
        return this.emailPbt;
    }
    
    public void setEmailPbt(String emailPbt) {
        this.emailPbt = emailPbt;
    }

    
    @Column(name="telefone_pbt", nullable=false, length=45)
    public String getTelefonePbt() {
        return this.telefonePbt;
    }
    
    public void setTelefonePbt(String telefonePbt) {
        this.telefonePbt = telefonePbt;
    }

    
    @Column(name="endereco_pbt", nullable=false, length=45)
    public String getEnderecoPbt() {
        return this.enderecoPbt;
    }
    
    public void setEnderecoPbt(String enderecoPbt) {
        this.enderecoPbt = enderecoPbt;
    }

    
    @Column(name="sexo", nullable=false, length=45)
    public int getsexo() {
        return this.sexo;
    }
    
    public void setsexo(int sexo) {
        this.sexo = sexo;
    }




}


